server:
  port: 8080

spring:
  application:
    name: list
  
  datasource:
    url: jdbc:mysql://localhost:3306/list?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create-drop
#      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Configuração padrão de usuário do Spring Security para ambiente de dev/testes
  # Isso evita que a senha mude toda vez que a aplicação reiniciar
  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN
